// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fail`, `parse`, `password`

/// Whether the app's data directory `dir` holds the leaf wallet of `mnemonic`.
Future<bool> leavesExists({required String dir, required String mnemonic}) =>
    RustLib.instance.api.crateApiLeavesLeavesExists(
      dir: dir,
      mnemonic: mnemonic,
    );

/// Joins an operator: creates the leaf wallet of `mnemonic` against the
/// operator and node `config_json` names (`{"server", "node_url",
/// "node_user"?, "node_password"?}`), pins the node's chain and the
/// operator's key, keeps it open, and restores whatever the operator and the
/// chain hold of this mnemonic's leaves. The answer is `{"info", "restore"}`.
Future<String> leavesJoin({
  required String dir,
  required String mnemonic,
  required String configJson,
}) => RustLib.instance.api.crateApiLeavesLeavesJoin(
  dir: dir,
  mnemonic: mnemonic,
  configJson: configJson,
);

/// Opens the leaf wallet of `mnemonic` and keeps it open; one already open
/// with this mnemonic is kept. `node_password` empty when the node needs none.
Future<void> leavesOpen({
  required String dir,
  required String mnemonic,
  required String nodePassword,
}) => RustLib.instance.api.crateApiLeavesLeavesOpen(
  dir: dir,
  mnemonic: mnemonic,
  nodePassword: nodePassword,
);

/// Runs one of the library's commands on the open wallet, `args_json` a JSON
/// object of its arguments. The answer is `{"result", "start"}`.
Future<String> leavesRun({required String command, required String argsJson}) =>
    RustLib.instance.api.crateApiLeavesLeavesRun(
      command: command,
      argsJson: argsJson,
    );

/// Closes the open wallet.
void leavesClose() => RustLib.instance.api.crateApiLeavesLeavesClose();

/// Whether a leaf wallet is open in this process.
bool leavesIsOpen() => RustLib.instance.api.crateApiLeavesLeavesIsOpen();

/// The scheduled job's pass: `sync`, then what arrived and when to wake
/// (`{"arrived", "schedule", "wake_in", "sync", "opened_for_the_job"}`, or
/// `{"joined": false}` when the phone holds no leaf wallet for `mnemonic`).
Future<String> leavesJob({
  required String dir,
  required String mnemonic,
  required String nodePassword,
}) => RustLib.instance.api.crateApiLeavesLeavesJob(
  dir: dir,
  mnemonic: mnemonic,
  nodePassword: nodePassword,
);

/// When the scheduled job must wake, in seconds, from the library's `schedule`
/// and `coins` answers: the schedule's `next_sync_at`, never more than a day
/// ahead while a coin is off the chain or a receive request waits; `None` when
/// nothing waits.
BigInt? leavesWakeIn({
  required String scheduleJson,
  required String coinsJson,
}) => RustLib.instance.api.crateApiLeavesLeavesWakeIn(
  scheduleJson: scheduleJson,
  coinsJson: coinsJson,
);
